// 페이지 데이터 객체
const pageData = {
  connect01: {
    // 커넥트 1
    leftImage: "/img/connect/connect01.jpg",
    right: [
      { src: "/img/connect/connect01/connect01_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect01/connect01_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect01/connect01_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect01/connect01_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect01/connect01_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect01/connect01_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect01/connect01_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect01/connect01_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect01/connect01_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect01/connect01_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect01/connect01_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect01/connect01_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect01/connect01_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect01/connect01_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect01/connect01_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect01/connect01_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect01/connect01_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect01/connect01_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect01/connect01_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect01/connect01_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect01/connect01_21.jpg", text: "애장품 21" },
    ],
  },
  connect02: {
    // 커넥트 2
    leftImage: "/img/connect/connect02.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect02에 대한 설명.",
    right: [
      { src: "/img/connect/connect02/connect02_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect02/connect02_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect02/connect02_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect02/connect02_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect02/connect02_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect02/connect02_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect02/connect02_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect02/connect02_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect02/connect02_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect02/connect02_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect02/connect02_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect02/connect02_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect02/connect02_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect02/connect02_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect02/connect02_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect02/connect02_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect02/connect02_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect02/connect02_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect02/connect02_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect02/connect02_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect02/connect02_21.jpg", text: "애장품 21" },
    ],
  },
  connect03: {
    // 커넥트 3
    leftImage: "/img/connect/connect03.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect03에 대한 설명.",
    right: [
      { src: "/img/connect/connect03/connect03_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect03/connect03_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect03/connect03_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect03/connect03_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect03/connect03_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect03/connect03_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect03/connect03_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect03/connect03_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect03/connect03_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect03/connect03_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect03/connect03_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect03/connect03_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect03/connect03_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect03/connect03_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect03/connect03_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect03/connect03_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect03/connect03_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect03/connect03_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect03/connect03_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect03/connect03_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect03/connect03_21.jpg", text: "애장품 21" },
    ],
  },
  connect04: {
    // 커넥트 4
    leftImage: "/img/connect/connect04.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect04에 대한 설명.",
    right: [
      { src: "/img/connect/connect04/connect04_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect04/connect04_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect04/connect04_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect04/connect04_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect04/connect04_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect04/connect04_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect04/connect04_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect04/connect04_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect04/connect04_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect04/connect04_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect04/connect04_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect04/connect04_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect04/connect04_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect04/connect04_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect04/connect04_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect04/connect04_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect04/connect04_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect04/connect04_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect04/connect04_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect04/connect04_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect04/connect04_21.jpg", text: "애장품 21" },
    ],
  },
  connect05: {
    // 커넥트 5
    leftImage: "/img/connect/connect05.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect05에 대한 설명.",
    right: [
      { src: "/img/connect/connect05/connect05_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect05/connect05_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect05/connect05_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect05/connect05_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect05/connect05_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect05/connect05_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect05/connect05_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect05/connect05_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect05/connect05_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect05/connect05_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect05/connect05_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect05/connect05_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect05/connect05_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect05/connect05_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect05/connect05_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect05/connect05_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect05/connect05_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect05/connect05_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect05/connect05_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect05/connect05_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect05/connect05_21.jpg", text: "애장품 21" },
    ],
  },
  connect06: {
    // 커넥트 6
    leftImage: "/img/connect/connect06.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect06에 대한 설명.",
    right: [
      { src: "/img/connect/connect06/connect06_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect06/connect06_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect06/connect06_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect06/connect06_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect06/connect06_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect06/connect06_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect06/connect06_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect06/connect06_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect06/connect06_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect06/connect06_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect06/connect06_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect06/connect06_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect06/connect06_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect06/connect06_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect06/connect06_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect06/connect06_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect06/connect06_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect06/connect06_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect06/connect06_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect06/connect06_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect06/connect06_21.jpg", text: "애장품 21" },
    ],
  },
  connect07: {
    // 커넥트 7
    leftImage: "/img/connect/connect07.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect07에 대한 설명.",
    right: [
      { src: "/img/connect/connect07/connect07_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect07/connect07_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect07/connect07_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect07/connect07_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect07/connect07_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect07/connect07_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect07/connect07_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect07/connect07_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect07/connect07_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect07/connect07_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect07/connect07_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect07/connect07_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect07/connect07_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect07/connect07_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect07/connect07_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect07/connect07_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect07/connect07_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect07/connect07_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect07/connect07_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect07/connect07_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect07/connect07_21.jpg", text: "애장품 21" },
    ],
  },
  connect08: {
    // 커넥트 8
    leftImage: "/img/connect/connect08.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect08에 대한 설명.",
    right: [
      { src: "/img/connect/connect08/connect08_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect08/connect08_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect08/connect08_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect08/connect08_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect08/connect08_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect08/connect08_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect08/connect08_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect08/connect08_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect08/connect08_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect08/connect08_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect08/connect08_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect08/connect08_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect08/connect08_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect08/connect08_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect08/connect08_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect08/connect08_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect08/connect08_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect08/connect08_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect08/connect08_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect08/connect08_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect08/connect08_21.jpg", text: "애장품 21" },
    ],
  },
  connect09: {
    // 커넥트 9
    leftImage: "/img/connect/connect09.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect09에 대한 설명.",
    right: [
      { src: "/img/connect/connect09/connect09_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect09/connect09_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect09/connect09_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect09/connect09_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect09/connect09_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect09/connect09_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect09/connect09_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect09/connect09_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect09/connect09_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect09/connect09_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect09/connect09_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect09/connect09_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect09/connect09_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect09/connect09_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect09/connect09_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect09/connect09_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect09/connect09_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect09/connect09_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect09/connect09_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect09/connect09_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect09/connect09_21.jpg", text: "애장품 21" },
    ],
  },
  connect10: {
    // 커넥트 10
    leftImage: "/img/connect/connect10.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect10에 대한 설명.",
    right: [
      { src: "/img/connect/connect10/connect10_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect10/connect10_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect10/connect10_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect10/connect10_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect10/connect10_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect10/connect10_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect10/connect10_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect10/connect10_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect10/connect10_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect10/connect10_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect10/connect10_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect10/connect10_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect10/connect10_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect10/connect10_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect10/connect10_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect10/connect10_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect10/connect10_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect10/connect10_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect10/connect10_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect10/connect10_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect10/connect10_21.jpg", text: "애장품 21" },
    ],
  },
  connect11: {
    // 커넥트 11
    leftImage: "/img/connect/connect11.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect11에 대한 설명.",
    right: [
      { src: "/img/connect/connect11/connect11_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect11/connect11_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect11/connect11_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect11/connect11_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect11/connect11_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect11/connect11_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect11/connect11_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect11/connect11_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect11/connect11_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect11/connect11_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect11/connect11_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect11/connect11_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect11/connect11_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect11/connect11_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect11/connect11_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect11/connect11_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect11/connect11_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect11/connect11_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect11/connect11_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect11/connect11_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect11/connect11_21.jpg", text: "애장품 21" },
    ],
  },
  connect12: {
    // 커넥트 12
    leftImage: "/img/connect/connect12.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect12에 대한 설명.",
    right: [
      { src: "/img/connect/connect12/connect12_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect12/connect12_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect12/connect12_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect12/connect12_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect12/connect12_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect12/connect12_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect12/connect12_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect12/connect12_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect12/connect12_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect12/connect12_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect12/connect12_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect12/connect12_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect12/connect12_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect12/connect12_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect12/connect12_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect12/connect12_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect12/connect12_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect12/connect12_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect12/connect12_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect12/connect12_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect12/connect12_21.jpg", text: "애장품 21" },
    ],
  },
  connect13: {
    // 커넥트 13
    leftImage: "/img/connect/connect13.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect13에 대한 설명.",
    right: [
      { src: "/img/connect/connect13/connect13_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect13/connect13_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect13/connect13_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect13/connect13_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect13/connect13_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect13/connect13_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect13/connect13_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect13/connect13_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect13/connect13_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect13/connect13_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect13/connect13_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect13/connect13_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect13/connect13_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect13/connect13_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect13/connect13_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect13/connect13_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect13/connect13_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect13/connect13_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect13/connect13_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect13/connect13_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect13/connect13_21.jpg", text: "애장품 21" },
    ],
  },
  connect14: {
    // 커넥트 14
    leftImage: "/img/connect/connect14.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect14에 대한 설명.",
    right: [
      { src: "/img/connect/connect14/connect14_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect14/connect14_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect14/connect14_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect14/connect14_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect14/connect14_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect14/connect14_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect14/connect14_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect14/connect14_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect14/connect14_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect14/connect14_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect14/connect14_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect14/connect14_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect14/connect14_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect14/connect14_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect14/connect14_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect14/connect14_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect14/connect14_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect14/connect14_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect14/connect14_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect14/connect14_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect14/connect14_21.jpg", text: "애장품 21" },
    ],
  },
  connect15: {
    // 커넥트 15
    leftImage: "/img/connect/connect15.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect15에 대한 설명.",
    right: [
      { src: "/img/connect/connect15/connect15_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect15/connect15_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect15/connect15_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect15/connect15_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect15/connect15_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect15/connect15_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect15/connect15_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect15/connect15_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect15/connect15_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect15/connect15_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect15/connect15_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect15/connect15_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect15/connect15_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect15/connect15_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect15/connect15_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect15/connect15_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect15/connect15_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect15/connect15_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect15/connect15_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect15/connect15_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect15/connect15_21.jpg", text: "애장품 21" },
    ],
  },
  connect16: {
    // 커넥트 16
    leftImage: "/img/connect/connect16.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect16에 대한 설명.",
    right: [
      { src: "/img/connect/connect16/connect16_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect16/connect16_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect16/connect16_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect16/connect16_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect16/connect16_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect16/connect16_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect16/connect16_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect16/connect16_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect16/connect16_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect16/connect16_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect16/connect16_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect16/connect16_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect16/connect16_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect16/connect16_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect16/connect16_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect16/connect16_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect16/connect16_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect16/connect16_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect16/connect16_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect16/connect16_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect16/connect16_21.jpg", text: "애장품 21" },
    ],
  },
  connect17: {
    // 커넥트 17
    leftImage: "/img/connect/connect17.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect17에 대한 설명.",
    right: [
      { src: "/img/connect/connect17/connect17_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect17/connect17_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect17/connect17_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect17/connect17_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect17/connect17_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect17/connect17_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect17/connect17_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect17/connect17_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect17/connect17_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect17/connect17_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect17/connect17_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect17/connect17_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect17/connect17_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect17/connect17_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect17/connect17_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect17/connect17_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect17/connect17_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect17/connect17_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect17/connect17_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect17/connect17_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect17/connect17_21.jpg", text: "애장품 21" },
    ],
  },
  connect18: {
    // 커넥트 18
    leftImage: "/img/connect/connect18.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect18에 대한 설명.",
    right: [
      { src: "/img/connect/connect18/connect18_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect18/connect18_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect18/connect18_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect18/connect18_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect18/connect18_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect18/connect18_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect18/connect18_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect18/connect18_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect18/connect18_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect18/connect18_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect18/connect18_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect18/connect18_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect18/connect18_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect18/connect18_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect18/connect18_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect18/connect18_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect18/connect18_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect18/connect18_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect18/connect18_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect18/connect18_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect18/connect18_21.jpg", text: "애장품 21" },
    ],
  },
  connect19: {
    // 커넥트 19
    leftImage: "/img/connect/connect19.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect19에 대한 설명.",
    right: [
      { src: "/img/connect/connect19/connect19_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect19/connect19_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect19/connect19_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect19/connect19_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect19/connect19_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect19/connect19_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect19/connect19_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect19/connect19_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect19/connect19_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect19/connect19_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect19/connect19_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect19/connect19_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect19/connect19_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect19/connect19_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect19/connect19_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect19/connect19_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect19/connect19_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect19/connect19_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect19/connect19_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect19/connect19_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect19/connect19_21.jpg", text: "애장품 21" },
    ],
  },
  connect20: {
    // 커넥트 20
    leftImage: "/img/connect/connect20.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect20에 대한 설명.",
    right: [
      { src: "/img/connect/connect20/connect20_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect20/connect20_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect20/connect20_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect20/connect20_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect20/connect20_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect20/connect20_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect20/connect20_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect20/connect20_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect20/connect20_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect20/connect20_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect20/connect20_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect20/connect20_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect20/connect20_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect20/connect20_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect20/connect20_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect20/connect20_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect20/connect20_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect20/connect20_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect20/connect20_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect20/connect20_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect20/connect20_21.jpg", text: "애장품 21" },
    ],
  },
  connect21: {
    // 커넥트 21
    leftImage: "/img/connect/connect21.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect21에 대한 설명.",
    right: [
      { src: "/img/connect/connect21/connect21_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect21/connect21_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect21/connect21_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect21/connect21_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect21/connect21_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect21/connect21_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect21/connect21_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect21/connect21_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect21/connect21_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect21/connect21_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect21/connect21_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect21/connect21_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect21/connect21_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect21/connect21_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect21/connect21_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect21/connect21_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect21/connect21_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect21/connect21_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect21/connect21_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect21/connect21_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect21/connect21_21.jpg", text: "애장품 21" },
    ],
  },
  connect22: {
    // 커넥트 22
    leftImage: "/img/connect/connect22.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect22에 대한 설명.",
    right: [
      { src: "/img/connect/connect22/connect22_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect22/connect22_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect22/connect22_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect22/connect22_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect22/connect22_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect22/connect22_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect22/connect22_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect22/connect22_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect22/connect22_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect22/connect22_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect22/connect22_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect22/connect22_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect22/connect22_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect22/connect22_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect22/connect22_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect22/connect22_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect22/connect22_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect22/connect22_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect22/connect22_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect22/connect22_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect22/connect22_21.jpg", text: "애장품 21" },
    ],
  },
  connect23: {
    // 커넥트 23
    leftImage: "/img/connect/connect23.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect23에 대한 설명.",
    right: [
      { src: "/img/connect/connect23/connect23_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect23/connect23_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect23/connect23_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect23/connect23_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect23/connect23_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect23/connect23_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect23/connect23_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect23/connect23_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect23/connect23_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect23/connect23_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect23/connect23_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect23/connect23_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect23/connect23_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect23/connect23_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect23/connect23_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect23/connect23_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect23/connect23_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect23/connect23_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect23/connect23_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect23/connect23_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect23/connect23_21.jpg", text: "애장품 21" },
    ],
  },
  connect24: {
    // 커넥트 24
    leftImage: "/img/connect/connect24.jpg",
    leftText: "Lorem ipsum dolor sit amet, connect24에 대한 설명.",
    right: [
      { src: "/img/connect/connect24/connect24_01.jpg", text: "애장품 1" },
      { src: "/img/connect/connect24/connect24_02.jpg", text: "애장품 2" },
      { src: "/img/connect/connect24/connect24_03.jpg", text: "애장품 3" },
      { src: "/img/connect/connect24/connect24_04.jpg", text: "애장품 4" },
      { src: "/img/connect/connect24/connect24_05.jpg", text: "애장품 5" },
      { src: "/img/connect/connect24/connect24_06.jpg", text: "애장품 6" },
      { src: "/img/connect/connect24/connect24_07.jpg", text: "애장품 7" },
      { src: "/img/connect/connect24/connect24_08.jpg", text: "애장품 8" },
      { src: "/img/connect/connect24/connect24_09.jpg", text: "애장품 9" },
      { src: "/img/connect/connect24/connect24_10.jpg", text: "애장품 10" },
      { src: "/img/connect/connect24/connect24_11.jpg", text: "애장품 11" },
      { src: "/img/connect/connect24/connect24_12.jpg", text: "애장품 12" },
      { src: "/img/connect/connect24/connect24_13.jpg", text: "애장품 13" },
      { src: "/img/connect/connect24/connect24_14.jpg", text: "애장품 14" },
      { src: "/img/connect/connect24/connect24_15.jpg", text: "애장품 15" },
      { src: "/img/connect/connect24/connect24_16.jpg", text: "애장품 16" },
      { src: "/img/connect/connect24/connect24_17.jpg", text: "애장품 17" },
      { src: "/img/connect/connect24/connect24_18.jpg", text: "애장품 18" },
      { src: "/img/connect/connect24/connect24_19.jpg", text: "애장품 19" },
      { src: "/img/connect/connect24/connect24_20.jpg", text: "애장품 20" },
      { src: "/img/connect/connect24/connect24_21.jpg", text: "애장품 21" },
    ],
  },
};

// 페이지 로드 함수
function loadPage() {
  const params = new URLSearchParams(window.location.search);
  const pageKey = params.get("page");

  if (pageKey && pageData[pageKey]) {
    const content = pageData[pageKey];

    // 왼쪽 이미지 설정
    document.getElementById("leftImage").src = content.leftImage;

    // 오른쪽 이미지와 텍스트 동적으로 생성
    const right = document.querySelector(".right");
    right.innerHTML = ""; // 기존 콘텐츠 초기화

    // large-layer에 데이터를 동적으로 추가
    right.innerHTML = `
  <div class="large-layer">
    ${content.right
      .map(
        (item) => `
        <div class="small-layer">
          <img src="${item.src}" class="layer-image" />
          <div class="layer-text">${item.text}</div>
        </div>
      `
      )
      .join("")}
  </div>
`;
  } else {
    console.error("해당 페이지 데이터를 찾을 수 없습니다.");
  }
}

// 페이지 로드 시 자동 호출
window.onload = loadPage;
